import "./globals.css";

import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

export const metadata: Metadata = {
  title: {
    default: "Eliza Pierce",
    template: "%s | Eliza Pierce",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body
          className={`relative ${GeistSans.className} bg-zinc-900 text-white h-screen antialiased scrollbar`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
